include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - avoid_print # Запрет принтов
    - always_use_package_imports # Полное название импорта