name: themoviedb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  flutter_secure_storage: ^5.1.0
  json_annotation: ^4.6.0
  flutter_localizations:
    sdk: flutter
  intl:
  youtube_player_flutter: ^8.1.0
  provider: ^6.0.3
  url_launcher: ^6.1.7
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: any
  build_runner: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
